# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  node:
    working_directory: ~/twilioCodepushDemo
    docker:
      - image: "circleci/node:8"
    steps:
      - checkout

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: ~/twilioCodepushDemo
          paths: .

  codepush: 
    working_directory: ~/twilioCodepushDemo
    docker:
      - image: "circleci/node:8"
    steps:
      - attach_workspace:
          at: ~/twilioCodepushDemo
      - run: sudo npm install -g appcenter-cli
      - run: appcenter codepush release-react -a david-alba/twilioCodepushDemo-1 --token $CODEPUSH_TOKEN --quiet --deployment-name Staging

  build: 
    working_directory: ~/twilioCodepushDemo
    docker:
      - image: "circleci/node:8"
    steps:
      - attach_workspace:
          at: ~/twilioCodepushDemo
      - run: sudo npm install -g appcenter-cli
      - run: appcenter build queue -a david-alba/twilioCodepushDemo-1 --branch master --token $CODEPUSH_TOKEN --quiet --deployment-name Staging


# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  # Name the workflow "Welcome"
  Test and deploy:
    # Run the welcome/run job in its own container
    jobs:
      - node:
         filters:
            tags:
              only:
                - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
            branches:
              only:
                - develop
                - master
      - hold: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
          requires: # We only run the "hold" job when test2 has succeeded
            - node
          filters:
            branches:
              only:
                - master
      - codepush:
          requires:
            - node
          filters:
            branches:
              only:
                - develop
      - codepush:
          requires:
            - hold
          filters:
            branches:
              only:
                - master
      - build:
          requires:
            - hold
          filters:
            tags:
              only:
                - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
